import type { GameSquare } from '../types/game';

export const BOARD_SQUARES: GameSquare[] = [
  { id: 0, type: 'START', label: 'DTC入社', description: 'デロイトへようこそ！ここから社長への長い道のりが始まります。', x: 0, y: 0 },
  { id: 1, type: 'NORMAL', label: '初期研修', description: 'ロジハン特訓。お祝いに2万円もらう。', x: 100, y: 0 },
  { id: 2, type: 'NORMAL', label: '初アサイン', description: 'アナリストとして初現場。緊張する。', x: 200, y: 0 },
  { id: 3, type: 'PROJECT_SUCCESS', label: 'PJ成功', description: '丁寧な議事録が好評！5万円ボーナス。', x: 300, y: 0 },
  { id: 4, type: 'TROUBLE', label: '徹夜作業', description: '資料修正が重なりヘトヘト。3万円支払う(健康維持費)。', x: 400, y: 0 },
  { id: 5, type: 'PAYDAY', label: '給料日', description: 'アナリストの給料日。', x: 500, y: 0 },
  { id: 6, type: 'TRAINING', label: 'スキルアップ', description: 'Udemyで猛勉強。5万円自己投資。', x: 600, y: 0 },
  { id: 7, type: 'NORMAL', label: '歓迎会', description: '同期との絆が深まる！', x: 700, y: 0 },
  { id: 8, type: 'STOP', label: 'C昇格審査', description: 'コンサルタントへの第1関門。', x: 700, y: 100 },
  { id: 9, type: 'PROMOTION', label: 'コンサル', description: 'コンサルタントに昇格！視座が上がる。', x: 600, y: 100 },
  { id: 10, type: 'PAYDAY', label: '給料日', description: '給料が上がった！', x: 500, y: 100 },
  { id: 11, type: 'PROJECT_SUCCESS', label: '提案成功', description: '新規PJT受注！10万円ボーナス。', x: 400, y: 100 },
  { id: 12, type: 'TROUBLE', label: '炎上案件', description: '火消しに奔走。精神修行。5万円支払う。', x: 300, y: 100 },
  { id: 13, type: 'MARRIAGE', label: 'ライフイベント', description: '結婚！ワークライフチョイス相談。', x: 200, y: 100 },
  { id: 14, type: 'NORMAL', label: '社内活動', description: 'Green Dot Awardに応募。', x: 100, y: 100 },
  { id: 15, type: 'PAYDAY', label: '給料日', description: '日々の努力の結晶。', x: 0, y: 100 },
  { id: 16, type: 'STOP', label: 'SC昇格審査', description: 'シニアコンサルタントへ。', x: 0, y: 200 },
  { id: 17, type: 'PROMOTION', label: 'SC昇格', description: 'チームをリードする立場に！', x: 100, y: 200 },
  { id: 18, type: 'PROJECT_SUCCESS', label: 'DX推進', description: '大規模変革をリード。20万円ボーナス。', x: 200, y: 200 },
  { id: 19, type: 'TROUBLE', label: 'スコープ拡大', description: 'クライアント要望が激増！10万円の追加対応コスト。', x: 300, y: 200 },
  { id: 20, type: 'PAYDAY', label: '給料日', description: 'SCは実入りが良い。', x: 400, y: 200 },
  { id: 21, type: 'TRAINING', label: 'DU研修', description: 'シンガポールでのリーダー研修。10万円投資。', x: 500, y: 200 },
  { id: 22, type: 'NORMAL', label: '登壇', description: '外部セミナーの講師に。ブランド向上！', x: 600, y: 200 },
  { id: 23, type: 'TROUBLE', label: '体調不良', description: '働きすぎに注意。5万円の通院費。', x: 700, y: 200 },
  { id: 24, type: 'STOP', label: 'M昇格審査', description: 'マネジャーへの登竜門。', x: 700, y: 300 },
  { id: 25, type: 'PROMOTION', label: 'M昇格', description: 'マネジメント業務開始。プレッシャー大。', x: 600, y: 300 },
  { id: 26, type: 'PAYDAY', label: '給料日', description: '責任に見合う報酬。', x: 500, y: 300 },
  { id: 27, type: 'PROJECT_SUCCESS', label: 'グローバルPJ', description: '世界を結ぶ変革。30万円ボーナス。', x: 400, y: 300 },
  { id: 28, type: 'TROUBLE', label: 'コンプラ研修', description: 'うっかりミスで指導。反省。', x: 300, y: 300 },
  { id: 29, type: 'NORMAL', label: 'メンタリング', description: '後輩が成長！やりがいを感じる。', x: 200, y: 300 },
  { id: 30, type: 'PAYDAY', label: '給料日', description: '安定感が出てきた。', x: 100, y: 300 },
  { id: 31, type: 'STOP', label: 'SM昇格審査', description: 'シニアマネジャーへ。', x: 0, y: 300 },
  { id: 32, type: 'PROMOTION', label: 'SM昇格', description: '組織運営に関わる。', x: 0, y: 400 },
  { id: 33, type: 'PROJECT_SUCCESS', label: '戦略案件', description: '業界首位の変革を実現。50万円ボーナス。', x: 100, y: 400 },
  { id: 34, type: 'TROUBLE', label: '予算削減', description: '厳しい状況を切り抜ける。20万円損失。', x: 200, y: 400 },
  { id: 35, type: 'PAYDAY', label: '給料日', description: 'かなりの高給。', x: 300, y: 400 },
  { id: 36, type: 'STOP', label: 'P昇格審査', description: 'ついにパートナーへ！', x: 400, y: 400 },
  { id: 37, type: 'PROMOTION', label: 'パートナー', description: 'デロイトの経営層へ。最高責任者の一人。', x: 500, y: 400 },
  { id: 38, type: 'PAYDAY', label: '給料日', description: '夢の報酬。', x: 600, y: 400 },
  { id: 39, type: 'STOP', label: '最終決戦', description: '次期社長候補としての選考。', x: 700, y: 400 },
  { id: 40, type: 'GOAL', label: 'DTC社長', description: '就任！「Make an Impact that Matters」の頂点へ！', x: 700, y: 500 },
];
